### ISSUE TITLE
Oracle JDBC driver does not accept Types.OTHER for setting null from DefaultOptionalArgument

### ISSUE THREAD

**Issue by dnowak** [dropwizard/dropwizard-java8#20]
Oracle driver throws exception when null is set from DefaultOptionalArgument using Types.OTHER

```
Caused by: java.sql.SQLException: Invalid column type: 1111
	at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:3900) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4406) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4388) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setNull(OraclePreparedStatementWrapper.java:1281) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
	at io.dropwizard.java8.jdbi.args.OptionalArgumentFactory$DefaultOptionalArgument.apply(OptionalArgumentFactory.java:27) ~[dropwizard-java8-jdbi-0.8.0-2.jar:na]
```

Everything is fine if Types.NULL is used to set null value.

Here I found the solution: https://github.com/jdbi/jdbi/issues/97

**Comment by joschi** [comment]
Fixed by merging #21.
